#!/bin/bash

iface="$1"
mac="$2"
mac="${mac,,}"		# downcase
mac="${mac//-/}"	# remove dashes
mac="${mac//:/}"	# remove colons

if [ "$#" != 2 ] ||
   ! [[ "$mac" =~ ^([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$ ]] ; then
	echo 1>&2 "Usage: `basename $0` <eth interface> <mac address>"
	exit 1
fi

# ks8851.c currently only supports writing a single byte
# note the byte order in the datasheet is bogus
/sbin/ethtool -E "$iface" magic 0x8851 offset 7 value 0x${BASH_REMATCH[1]}
/sbin/ethtool -E "$iface" magic 0x8851 offset 6 value 0x${BASH_REMATCH[2]}
/sbin/ethtool -E "$iface" magic 0x8851 offset 5 value 0x${BASH_REMATCH[3]}
/sbin/ethtool -E "$iface" magic 0x8851 offset 4 value 0x${BASH_REMATCH[4]}
/sbin/ethtool -E "$iface" magic 0x8851 offset 3 value 0x${BASH_REMATCH[5]}
/sbin/ethtool -E "$iface" magic 0x8851 offset 2 value 0x${BASH_REMATCH[6]}
