.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016-2021 KUNBUS GmbH
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH piSerial 8 "February 22, 2021"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
piSerial \- retrieve the RevPi serial number
.SH SYNOPSIS
.B piSerial
.RI [ options ]
.SH DESCRIPTION
.B piSerial
allows retrieving the RevPi's serial number and generating the factory-default
password. Revolution Pi is a set of IoT products based on the Raspberry Pi and
geared towards industrial usage.
.SH OPTIONS
.TP
.B \-p
Show initial password.
.TP
.B \-s
Show serial number.
.TP
.B \-v
Print the version and exit.
.TP
If no print option is specified both, the serial number and the password are
printed.
.SH SEE ALSO
For more information on Revolution Pi visit
.IR https://revolutionpi.kunbus.com
