#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright: 2022 KUNBUS GmbH
#

cm1-detection() {
    grep -m 1 "model name" /proc/cpuinfo | grep -q v6l
    return $?
}

# Check existance of HAT EEPROM according to document:
# https://github.com/RevolutionPi/revpi-hat-eeprom/blob/master/docs/RevPi-HAT-EEPROM-Format.md#custom-atoms
has-hat-eeprom() {
	if [ -e /proc/device-tree/hat/custom_1 ]; then
		return 0;
	fi
	return 1;
}
